Repository powsybl/pypowsybl, pull requests merged in 2023-11, with the labels that each got.

#671 Update voltage initializer to open reac version 0.3
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/voltage_initializer.rst
  java/pom.xml
  java/src/main/java/com/powsybl/python/voltageinit/VoltageInitializerCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/voltage_initializer/impl/voltage_initializer.py
  tests/test_voltage_initializer.py
Labels: status: ready to be merged, PR: next-release

#672 Save network to a binary buffer
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/user_guide/network.rst
  java/src/main/java/com/powsybl/python/commons/CTypeUtil.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/ZipMemDataSource.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: PR: next-release

#662 Add target v sensitivity on current and reactive power
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/user_guide/sensitivity.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisCFunctions.java
  java/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisContext.java
  java/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisResultContext.java
  java/src/test/java/com/powsybl/python/sensitivity/SensitivityAnalysisTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/sensitivity/__init__.py
  pypowsybl/sensitivity/impl/ac_sensitivity_analysis.py
  pypowsybl/sensitivity/impl/ac_sensitivity_analysis_result.py
  pypowsybl/sensitivity/impl/dc_sensitivity_analysis.py
  pypowsybl/sensitivity/impl/dc_sensitivity_analysis_result.py
  pypowsybl/sensitivity/impl/sensitivity.py
  pypowsybl/sensitivity/impl/sensitivity_analysis_result.py
  tests/test_sensitivity_analysis.py
Labels: status: ready to be merged, PR: next-release

#668 Release v1.1.0
  java/pom.xml
  pypowsybl/__init__.py
Labels: status: ready to be merged

#674 Remove python 3.7 compatibility
  .github/workflows/full-ci.yml
  README.md
  requirements.txt
  setup.cfg
  sonar-project.properties
Labels: breaking change
