Repository powsybl/pypowsybl, pull requests merged in 2023-02, with the labels that each got.

#565 add topology kind attribute for voltage levels
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready-for-review

#545 [Network modifications] Create voltage level topology from scratch.
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/dataframe/network/modifications/DataframeNetworkModificationType.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/NetworkModification.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/NetworkModifications.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/VoltageLevelTopologyCreation.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  java/src/main/java/com/powsybl/python/network/PyPowsyblNetworksProvider.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
  tests/test_network_elements_creation.py
  tests/test_network_modification.py
Labels: status: ready to be merged

#570 fix optional attributes for creation and docstring
  pypowsybl/network.py
  tests/test_network_elements_creation.py
Labels: status: ready-for-review

#564 Allowing multiple dataframes extensions + exposing secondary voltage level extension
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/AbstractSingleDataframeNetworkExtension.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ActivePowerControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/BranchObservabilityDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/BusBarSectionPositionDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ConnectablePositionDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/CoordinatedReactiveControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/EntsoeAreaDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ExtensionDataframeKey.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/GeneratorEntsoeCategoryDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/GeneratorShortCircuitDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/HvdcAngleDroopActivePowerControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/HvdcOperatorActivePowerRangeDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/IdentifiableShortCircuitDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/InjectionObservabilityDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/LoadDetailDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/MeasurementsDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/MergedXnodeDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/NetworkExtensionDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/NetworkExtensions.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/SlackTerminalDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/StandByAutomatonDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/XnodeDataframeProvider.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/java/com/powsybl/dataframe/network/adders/NetworkElementAddersTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network_extensions.py
Labels: status: ready to be merged

#543 [Network modifications] Wrap CreateCouplingDevice.
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/dataframe/network/modifications/CouplingDeviceCreation.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/DataframeNetworkModificationType.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/NetworkModifications.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network_modification.py
Labels: status: ready to be merged

#573 remove useless version in pom
  java/pom.xml
Labels: status: ready to be merged

#566 [Network modifications] [Fix] Allow creation of multiple branches.
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractFeederBaysSeries.java
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  tests/test_network.py
  tests/test_network_modification.py
Labels: status: ready to be merged

#571 [Network modifications] Allow to create injections and branches with bay in BUS_BREAKER topology
  docs/user_guide/network.rst
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractBranchSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractFeederBaysSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractSimpleAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/BatteryDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/DanglingLineDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/FeederBaysLineSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/FeederBaysTwtSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/GeneratorDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/LccStationDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/LoadDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkUtils.java
  java/src/main/java/com/powsybl/dataframe/network/adders/ShuntDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/SvcDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/TwoWindingsTransformerSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/VscStationDataframeAdder.java
  pypowsybl/network.py
  tests/test_network_modification.py
Labels: status: ready to be merged

#574 upgrade to powsybl dependencies 2023.0.1
  java/pom.xml
  tests/test_loadflow.py
Labels: status: ready to be merged

#559 [Network Modifications] Add documentation
  docs/_static/images/node_breaker_network/test_network_vl1_after_adding_everything.svg
  docs/_static/images/node_breaker_network/test_network_vl1_after_adding_extensions.svg
  docs/_static/images/node_breaker_network/test_network_vl1_after_adding_load.svg
  docs/_static/images/node_breaker_network/test_network_vl1_before_adding_extensions.svg
  docs/_static/images/node_breaker_network/test_network_vl1_only_bbs_without_extensions.svg
  docs/_static/images/node_breaker_network/test_network_vl1_parallel_bbs.svg
  docs/_static/images/node_breaker_network/test_network_vl1_with_new_line2.svg
  docs/_static/images/node_breaker_network/test_network_vl1_with_transformer.svg
  docs/_static/images/node_breaker_network/test_network_vl2_after_adding_everything.svg
  docs/_static/images/node_breaker_network/test_network_vl2_after_adding_extensions.svg
  docs/_static/images/node_breaker_network/test_network_vl2_before_adding_extensions.svg
  docs/_static/images/node_breaker_network/test_network_vl2_only_bbs.svg
  docs/_static/images/node_breaker_network/test_network_vl2_with_new_line2.svg
  docs/_static/images/node_breaker_network/test_network_vl3_only_bbs.svg
  docs/_static/images/node_breaker_network/test_network_vl3_with_coupling_device.svg
  docs/_static/images/node_breaker_network/test_network_vl3_with_transformer.svg
  docs/user_guide/network.rst
Labels: status: in-progress

#520 Dynawaltz integration
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/dynamic.rst
  docs/reference/index.rst
  docs/user_guide/dynamic.rst
  docs/user_guide/index.rst
  java/pom.xml
  java/src/main/java/com/powsybl/dataframe/dynamic/CurvesSeries.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/AbstractBlackBoxAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/AlphaBetaLoadAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/CurrentLimitAutomatonAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/DynamicMappingAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/DynamicMappingAdderFactory.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/GeneratorSynchronousAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/GeneratorSynchronousFourWindingsAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/GeneratorSynchronousFourWindingsProportionalRegulationsAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/GeneratorSynchronousThreeWindingsAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/GeneratorSynchronousThreeWindingsProportionalRegulationsAdder.java
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/OneTransformerLoadAdder.java
  java/src/main/java/com/powsybl/python/commons/CTypeUtil.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/dynamic/CurveMappingSupplier.java
  java/src/main/java/com/powsybl/python/dynamic/DynamicModelMapper.java
  java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationCFunctions.java
  java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationContext.java
  java/src/main/java/com/powsybl/python/dynamic/EventSupplier.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/dynamic.py
  pypowsybl/utils/dataframes.py
  tests/test_dynamic.py
Labels: status: ready to be merged

#577 expose add nodes infos for single line diagram
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#576 Release v0.21.0
  java/pom.xml
  pypowsybl/__init__.py
Labels: status: ready to be merged

#578 add new security analysis tests
  java/src/main/java/com/powsybl/python/network/PyPowsyblNetworksProvider.java
  tests/test_security_analysis.py
Labels: status: ready to be merged

#579 allow to change component library on single line diagram
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/SingleLineDiagramUtil.java
  java/src/main/resources/META-INF/native-image/com.powsybl/powsybl-single-line-diagram-core/resource-config.json
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#581 Use ...Provider.findAll()
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCFunctions.java
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCUtils.java
  java/src/main/java/com/powsybl/python/security/SecurityAnalysisCFunctions.java
  java/src/main/java/com/powsybl/python/security/SecurityAnalysisCUtils.java
  java/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisCFunctions.java
  java/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisCUtils.java
Labels: status: ready to be merged
