Repository powsybl/pypowsybl, pull requests merged in 2023-10, with the labels that each got.

#660 fix network visualization documentation
  docs/user_guide/network_visualization.rst
Labels: documentation, status: ready to be merged

#632 Modify powsybl-diagram apis
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkAreaDiagramUtil.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/SingleLineDiagramUtil.java
  java/src/test/java/com/powsybl/python/network/SingleLineDiagramUtilTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/__init__.py
  pypowsybl/network/impl/layout_parameters.py
  pypowsybl/network/impl/network.py
  pypowsybl/network/impl/sld_parameters.py
  tests/test_network.py
Labels: breaking change, status: ready to be merged, PR: next-release

#663 refactoring warnings of java part
  java/src/main/java/com/powsybl/dataframe/AbstractDataframeMapper.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ActivePowerControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/BranchObservabilityDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/BranchObservabilityDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ConnectablePositionDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ConnectablePositionDataframeProvider.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/flow_decomposition/FlowDecompositionContext.java
  java/src/main/java/com/powsybl/python/loadflow/validation/LoadFlowValidationCFunctions.java
  java/src/main/java/com/powsybl/python/logging/PyLoggingUtil.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/NetworkUtil.java
Labels: status: ready-for-review

#661 Sub-networks implementation
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/user_guide/network.rst
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: PR: next-release

#659 Remove useless logs
  java/src/main/java/com/powsybl/python/logging/LoggingCFunctions.java
  java/src/main/resources/logback.xml
Labels: PR: next-release

#666 Set compatibility mode for native image build option
  cpp/CMakeLists.txt
Labels: bug, status: ready to be merged
