Repository powsybl/pypowsybl, pull requests merged in 2023-01, with the labels that each got.

#544 Wrap revertConnectVoltageLevelOnLine and revertCreateLineOnLine.
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#550 [Network modifications] Fix: remove compulsory attribute "voltage level" in the dataframe to create two windings transformer bay.
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready-for-review

#483 get more information about extension
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/dataframe/network/ExtensionInformation.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ActivePowerControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/BranchObservabilityDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/BusBarSectionPositionDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ConnectablePositionDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/EntsoeAreaDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/GeneratorEntsoeCategoryDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/GeneratorShortCircuitDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/HvdcAngleDroopActivePowerControlDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/HvdcOperatorActivePowerRangeDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/IdentifiableShortCircuitDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/InjectionObservabilityDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/LoadDetailDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/MeasurementsDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/MergedXnodeDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/NetworkExtensionDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/NetworkExtensions.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/SlackTerminalDataframeProvider.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/XnodeDataframeProvider.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network_extensions.py
Labels: documentation, status: ready to be merged

#527 add identifiable, injection, branch and terminal dataframes in network
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  docs/reference/network.rst
  docs/user_guide/network.rst
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#537 Add deep removal for network elements
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/python/network/Dataframes.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/PyPowsyblNetworksProvider.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#551 [Flow Decomposition] Update to Entsoe 2.1.0
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  data/19700101_0000_FO4_UX1.uct
  docs/reference/flowdecomposition.rst
  docs/user_guide/flowdecomposition.rst
  java/pom.xml
  java/src/main/java/com/powsybl/python/flow_decomposition/FlowDecompositionCFunctions.java
  java/src/main/java/com/powsybl/python/flow_decomposition/FlowDecompositionContext.java
  java/src/main/java/com/powsybl/python/flow_decomposition/XnecWithDecompositionContext.java
  java/src/main/java/com/powsybl/python/network/Dataframes.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/flowdecomposition.py
  tests/test_flow_decomposition.py
Labels: status: ready-for-review, breaking change

#556 add coordinatedReactiveControl extension
  java/src/main/java/com/powsybl/dataframe/network/extensions/CoordinatedReactiveControlDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/CoordinatedReactiveControlDataframeProvider.java
  tests/test_network_extensions.py
Labels: status: ready-for-review

#511 Wrap replaceTeePointByVoltageLevelOnLine
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#553 Allowing to modify load flow validation parameters
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/loadflow.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/loadflow/validation/LoadFlowValidationCFunctions.java
  java/src/test/java/com/powsybl/python/loadflow/validation/LoadFlowValidationTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/loadflow.py
  pypowsybl/security.py
  pypowsybl/sensitivity.py
  tests/test_loadflow.py
  tests/test_network_extensions.py
Labels: status: ready to be merged
