Repository powsybl/pypowsybl, pull requests merged in 2024-07, with the labels that each got.

#756 Add support of dc_power_factor Load Flow Parameter
  cpp/powsybl-cpp/powsybl-api.h
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/loadflow.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCFunctions.java
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCUtils.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/loadflow/impl/parameters.py
  tests/test_loadflow.py
Labels: status: ready-for-review

#791 adding documentation for reduce function
  docs/user_guide/network.rst
  pypowsybl/network/impl/network.py
Labels: documentation, status: ready to be merged

#781 add get_matrix_multi_substation_single_line_diagram
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/reference/network.rst
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/SingleLineDiagramUtil.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#785 Current feeder info
  cpp/powsybl-cpp/powsybl-api.h
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/_static/images/ieee14_SldParam_displaycurrentfeederinfo.svg
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/sld_parameters.py
  tests/test_network.py
Labels: status: ready to be merged

#798 Fix CI : regain compatibility with node16 for the CI
  .github/workflows/dev-ci.yml
  .github/workflows/full-ci.yml
Labels: status: ready to be merged

#797 Fix multi substation sld svg
  java/src/main/java/com/powsybl/python/commons/CTypeUtil.java
  tests/test_network.py
Labels: status: ready to be merged

#805 add documentation for hvdc lines
  pypowsybl/network/impl/network.py
Labels: documentation

#799 Display units feeder info
  cpp/powsybl-cpp/powsybl-api.h
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/_static/images/ieee14_SldParam_activepowerunit.svg
  docs/_static/images/ieee14_SldParam_currentunit.svg
  docs/_static/images/ieee14_SldParam_reactivepowerunit.svg
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/sld_parameters.py
  tests/test_network.py
Labels: status: ready to be merged

#806 allows using empty strings in the SLD multi-subs matrix parameter
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/network/SingleLineDiagramUtil.java
  java/src/test/java/com/powsybl/python/network/SingleLineDiagramUtilTest.java
  tests/test_network.py
Labels: status: ready to be merged
