Repository powsybl/pypowsybl, pull requests merged in 2024-10, with the labels that each got.

#847 Add documentation about Node/Breaker and Bus/Breaker topology
  docs/reference/network.rst
  docs/reference/network/bus_breaker_topology.rst
  docs/reference/network/node_breaker_topology.rst
  pypowsybl/network/impl/bus_breaker_topology.py
  pypowsybl/network/impl/node_breaker_topology.py
Labels: documentation, status: ready-for-review

#845 Flow decomposition: Add max current overload rescaler
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  pypowsybl/_pypowsybl.pyi
  tests/test_flow_decomposition.py
Labels: PR: next-release

#861 Improve load flow provider_parameters documentation
  docs/user_guide/loadflow.rst
Labels: documentation, PR: next-release

#820 Python 3.13
  .github/workflows/dev-ci.yml
  .github/workflows/full-ci.yml
  .github/workflows/release-ci.yml
  README.md
  requirements.txt
  setup.cfg
Labels: PR: next-release

#862 Add reference priorities iIDM extension bindings
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkUtils.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ReferencePrioritiesDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/ReferencePrioritiesDataframeProvider.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  tests/test_network_extensions.py
Labels: status: ready-for-review, PR: next-release

#859 Add mapping to all operational limits, allow to modify selected set of limits for each element
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/user_guide/network.rst
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/dataframe/network/adders/LimitsDataframeAdderKey.java
  java/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkUtil.java
  java/src/main/java/com/powsybl/python/network/TemporaryLimitData.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/java/com/powsybl/dataframe/network/adders/NetworkElementAddersTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
  tests/test_network_elements_creation.py
Labels: PR: next-release

#786 Pandapower converter
  data/educ_case14_storage.json
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractBranchSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/InjectionSeries.java
  mypy.ini
  pypowsybl/network/__init__.py
  pypowsybl/network/impl/pandapower_converter.py
  pypowsybl/utils/impl/dataframes.py
  requirements.txt
  setup.cfg
  tests/test_pandapower.py
Labels: PR: next-release

#827 Cgmes metadata storage extension
  java/pom.xml
  java/src/main/java/com/powsybl/dataframe/network/extensions/CgmesMetadataModelDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/CgmesMetadataModelDataframeProvider.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/java/com/powsybl/dataframe/network/adders/NetworkElementAddersTest.java
  tests/test_network_extensions.py
Labels: PR: next-release

#840 Add Network area model support
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/reference/network.rst
  docs/user_guide/network.rst
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AreaBoundariesDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AreaDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AreaVoltageLevelsDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkElementAdders.java
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkUtils.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/Networks.java
  java/src/main/java/com/powsybl/python/network/PyPowsyblNetworksProvider.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/java/com/powsybl/dataframe/network/adders/NetworkElementAddersTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/__init__.py
  pypowsybl/network/impl/network.py
  pypowsybl/network/impl/network_creation_util.py
  tests/test_network.py
Labels: status: ready-for-review, PR: next-release
