Repository powsybl/pypowsybl, pull requests merged in 2024-11, with the labels that each got.

#878 Fills the metadata attribute, in the get NAD's output
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: PR: next-release

#881 Fix bus/breaker topology in case of no connected terminal present
  java/src/main/java/com/powsybl/python/network/Dataframes.java
  java/src/main/java/com/powsybl/python/network/NetworkUtil.java
  java/src/test/java/com/powsybl/python/network/NetworkUtilTest.java
  tests/test_network.py
Labels: bug, PR: next-release

#873 Support creation and removal of internal connections
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/adders/InternalConnectionDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkElementAdders.java
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkUtils.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network_elements_creation.py
Labels: PR: next-release

#877 Add Load Flow specific parameters categories
  docs/user_guide/loadflow.rst
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCUtils.java
  pypowsybl/loadflow/impl/loadflow.py
Labels: PR: next-release

#889 Get import supported extensions
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/__init__.py
  pypowsybl/network/impl/util.py
  tests/test_network.py
Labels: PR: next-release

#884 Fix pytest and pylint warnings
  .pylintrc
  pypowsybl/__init__.py
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  pypowsybl/network/impl/network_element_modification_util.py
  pypowsybl/network/impl/pandapower_converter.py
  pypowsybl/utils/impl/dataframes.py
  pypowsybl/voltage_initializer/impl/voltage_initializer_parameters.py
  requirements.txt
  tests/test_java_perunit.py
  tests/test_loadflow.py
  tests/test_network.py
  tests/test_network_elements_creation.py
  tests/test_network_modification.py
  tests/test_per_unit.py
  tests/test_security_analysis.py
  tests/test_sensitivity_analysis.py
Labels: status: ready-for-review, PR: next-release

#880 Bus/Breaker view buses: add column with bus ID in bus view
  docs/reference/network.rst
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/python/network/Dataframes.java
  java/src/main/java/com/powsybl/python/network/NetworkUtil.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/java/com/powsybl/python/network/NetworkUtilTest.java
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: status: ready-for-review, PR: next-release

#821 Adding dangling line's generation part mapping
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/dataframe/network/adders/DanglingLineDataframeAdder.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/java/com/powsybl/dataframe/network/adders/NetworkElementAddersTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  pypowsybl/network/impl/network_element_modification_util.py
  tests/test_network.py
Labels: PR: next-release
