Repository powsybl/pypowsybl, pull requests merged in 2024-02, with the labels that each got.

#698 Fix readme mentioning Python 3.7 support
  README.md
Labels: documentation, status: ready to be merged

#700 [Shortcircuits] Units of currents are in A and not kA
  pypowsybl/shortcircuit/impl/parameters.py
  pypowsybl/shortcircuit/impl/short_circuit_analysis.py
  pypowsybl/shortcircuit/impl/short_circuit_analysis_result.py
Labels: status: ready to be merged

#708 Fix Security Analysis doc mentioning Sensitivity Analysis
  docs/user_guide/dynamic.rst
  docs/user_guide/loadflow.rst
  docs/user_guide/network.rst
  docs/user_guide/network_visualization.rst
  docs/user_guide/security.rst
  docs/user_guide/sensitivity.rst
  pypowsybl/dynamic/impl/event_mapping.py
  pypowsybl/dynamic/impl/model_mapping.py
  pypowsybl/network/impl/network.py
  pypowsybl/security/impl/parameters.py
  pypowsybl/security/impl/security.py
  pypowsybl/security/impl/security_analysis_result.py
  pypowsybl/security/impl/util.py
  pypowsybl/sensitivity/impl/util.py
  pypowsybl/utils/impl/dataframes.py
Labels: documentation, status: ready to be merged

#704 Upgrade dependencies v2024.0.1
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/user_guide/dynamic.rst
  docs/user_guide/flowdecomposition.rst
  docs/user_guide/network.rst
  docs/user_guide/security.rst
  java/.mvn/wrapper/maven-wrapper.jar
  java/pom.xml
  java/src/main/java/com/powsybl/dataframe/dynamic/adders/GeneratorSynchronousAdder.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/extensions/SecondaryVoltageControlDataframeProvider.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationCFunctions.java
  java/src/main/java/com/powsybl/python/dynamic/EventSupplier.java
  java/src/main/java/com/powsybl/python/dynamic/PythonDynamicModelsSupplier.java
  java/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/src/test/resources/nad.svg
  java/src/test/resources/sld.svg
  pypowsybl/_pypowsybl.pyi
  pypowsybl/dynamic/impl/event_mapping.py
  pypowsybl/dynamic/impl/util.py
  pypowsybl/security/__init__.py
  tests/battery.xiidm
  tests/test_dynamic.py
  tests/test_flow_decomposition.py
  tests/test_loadflow.py
  tests/test_network.py
  tests/test_security_analysis.py
Labels: status: ready to be merged

#710 refactor voltage initializer module
  pypowsybl/voltage_initializer/__init__.py
  pypowsybl/voltage_initializer/impl/voltage_initializer.py
  pypowsybl/voltage_initializer/impl/voltage_initializer_parameters.py
  pypowsybl/voltage_initializer/impl/voltage_initializer_results.py
Labels: status: ready to be merged

#689 Empty list of voltage level ids as NAD nominal voltage filter input
  docs/_static/images/ieee300_subnetwork_vl1_filtered.svg
  docs/_static/images/ieee30_subnetwork_filtered_no_id.svg
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/network/NetworkAreaDiagramUtil.java
  tests/test_network.py
Labels: bug, status: ready to be merged

#711 Documentation fixes and additions
  docs/_static/images/ieee30_subnetwork_filtered_no_vl_id.svg
  docs/reference/dynamic.rst
  docs/reference/security.rst
  docs/user_guide/index.rst
  docs/user_guide/security.rst
  pypowsybl/security/impl/security.py
Labels: documentation, status: ready-for-review

#701 [Network modifications] Fix: no exception should be thrown if boolean throwException is false
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractBranchSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractFeederBaysSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/AbstractSimpleAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/BatteryDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/DanglingLineDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/GeneratorDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/LccStationDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/LineSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/LoadDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/NetworkUtils.java
  java/src/main/java/com/powsybl/dataframe/network/adders/ShuntDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/SvcDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/adders/TwoWindingsTransformerSeries.java
  java/src/main/java/com/powsybl/dataframe/network/adders/VscStationDataframeAdder.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/CreateLineFeeder.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/CreateTwoWindingsTransformer.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/ReplaceTeePointByVoltageLevelOnLine.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/RevertConnectVoltageLevelOnLine.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/RevertCreateLineOnLine.java
  java/src/main/java/com/powsybl/dataframe/network/modifications/VoltageLevelTopologyCreation.java
  java/src/main/java/com/powsybl/python/network/NetworkModificationsCFunctions.java
  java/src/main/java/com/powsybl/python/security/SecurityAnalysisCFunctions.java
  tests/test_network_modification.py
Labels: bug, status: ready to be merged

#697 Add new method for multi-substation sld drawing
  cpp/src/bindings.cpp
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/_static/images/ieee14_s1_s2_s3_s4.svg
  docs/reference/network.rst
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/commons/CTypeUtil.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/network/SingleLineDiagramUtil.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: status: ready to be merged

#709 Load Flow API updates
  README.md
  cpp/src/bindings.cpp
  cpp/src/pypowsybl-api.h
  cpp/src/pypowsybl.cpp
  cpp/src/pypowsybl.h
  docs/reference/loadflow.rst
  docs/user_guide/loadflow.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCFunctions.java
  java/src/main/java/com/powsybl/python/loadflow/LoadFlowCUtils.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/loadflow/__init__.py
  pypowsybl/loadflow/impl/component_result.py
  pypowsybl/loadflow/impl/parameters.py
  pypowsybl/loadflow/impl/slack_bus_result.py
  tests/test_flow_decomposition.py
  tests/test_loadflow.py
Labels: status: ready-for-review, breaking change

#712 [Network modifications] Default values for raise_exception is True.
  docs/user_guide/network.rst
  pypowsybl/network/impl/network_element_modification_util.py
  tests/test_network_modification.py
Labels: breaking change, status: ready to be merged

#713 Release v1.3.0
  java/pom.xml
  pypowsybl/__init__.py
Labels: status: ready to be merged

#716 add missing method in documentation
  docs/reference/network.rst
Labels: documentation, status: ready-for-review
