Repository powsybl/pypowsybl, pull requests merged in 2024-06, with the labels that each got.

#737 Add new OpenReac scaling factor parameters
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/voltage_initializer.rst
  java/src/main/java/com/powsybl/python/voltageinit/VoltageInitializerCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/voltage_initializer/impl/voltage_initializer_parameters.py
  tests/test_voltage_initializer.py
Labels: status: ready to be merged

#757 Add interface of new OpenReac parameters
  cpp/powsybl-cpp/powsybl-api.h
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/voltage_initializer.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/voltageinit/VoltageInitializerCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/voltage_initializer/__init__.py
  pypowsybl/voltage_initializer/impl/voltage_initializer_parameters.py
  tests/test_voltage_initializer.py
Labels: status: ready to be merged

#766 Fix generator creation name
  java/src/main/java/com/powsybl/dataframe/network/adders/GeneratorDataframeAdder.java
  tests/test_network_elements_creation.py
Labels: status: ready to be merged

#767 improve NadParameters documentation
  docs/user_guide/network_visualization.rst
Labels: documentation, status: ready to be merged

#773 Edge info displayed
  cpp/powsybl-cpp/powsybl-api.h
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/network_visualization.rst
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/__init__.py
  pypowsybl/network/impl/nad_parameters.py
  tests/test_network.py
Labels: status: ready to be merged

#732 Remove deprecated attributes in network modification functions
  pypowsybl/network/impl/network_element_modification_util.py
  tests/test_network_modification.py
Labels: breaking change, status: ready to be merged

#775 add Sld parameters in doc
  docs/_static/images/SldParam_topologicalcoloringfalse.svg
  docs/_static/images/SldParam_topologicalcoloringtrue.svg
  docs/_static/images/ieee14_SldParam_centername.svg
  docs/_static/images/ieee14_SldParam_complib_flatdesign.svg
  docs/_static/images/ieee14_SldParam_default.svg
  docs/_static/images/ieee14_SldParam_diagonallabel.svg
  docs/_static/images/ieee14_SldParam_nodesinfos.svg
  docs/_static/images/ieee14_SldParam_tooltipenabledtrue.png
  docs/_static/images/ieee14_SldParam_topologicalcoloringfalse.svg
  docs/_static/images/ieee14_SldParam_topologicalcoloringtrue.svg
  docs/_static/images/ieee14_SldParam_usename.svg
  docs/user_guide/network_visualization.rst
Labels: status: ready to be merged
