Repository powsybl/pypowsybl, pull requests merged in 2024-12, with the labels that each got.

#908 Remove builds on macos-12 runners
  .github/workflows/dev-ci.yml
  .github/workflows/full-ci.yml
  .github/workflows/release-ci.yml
  .github/workflows/snapshot-ci.yml
Labels: breaking change

#900 Fix non-linear shunt compensator section number
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  tests/test_network.py
  tests/test_network_elements_creation.py
  tests/test_network_modification.py
Labels: bug, status: ready-for-review

#915 Fix ODRE geo data loader
  java/pom.xml
  java/src/main/resources/META-INF/native-image/com.fasterxml.jackson.core/jackson-databind/reflect-config.json
  java/src/main/resources/META-INF/native-image/com.powsybl/powsybl-iidm-geodata/reflect-config.json
Labels: bug, December 2024 release

#909 Get network elements properties as data frame
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/reference/network.rst
  java/src/main/java/com/powsybl/dataframe/DataframeElementType.java
  java/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  tests/test_network.py
Labels: status: ready-for-review, December 2024 release

#913 Enable download of documentation in pdf format
  .readthedocs.yaml
Labels: Release 03/2025

#868 Open Rao integration
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/CMakeLists.txt
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/CMakeLists.txt
  cpp/pypowsybl-java/powsybl-api.h
  data/rao/rao_crac.json
  data/rao/rao_glsk.xml
  data/rao/rao_network.uct
  data/rao/rao_parameters.json
  java/pom.xml
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/src/main/java/com/powsybl/python/rao/RaoCFunctions.java
  java/src/main/java/com/powsybl/python/rao/RaoContext.java
  pypowsybl/__init__.py
  pypowsybl/_pypowsybl.pyi
  pypowsybl/rao/__init__.py
  pypowsybl/rao/impl/__init__.py
  pypowsybl/rao/impl/parameters.py
  pypowsybl/rao/impl/rao.py
  pypowsybl/rao/impl/rao_result.py
  pypowsybl/rao/impl/util.py
  tests/test_rao.py
Labels: December 2024 release

#914 Dynamic simulation output variables supplier
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/reference/dynamic.rst
  docs/user_guide/dynamic.rst
  integration_tests/test_dynawo.py
  java/src/main/java/com/powsybl/dataframe/dynamic/CurvesSeries.java
  java/src/main/java/com/powsybl/dataframe/dynamic/OutputVariablesSeries.java
  java/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/src/main/java/com/powsybl/python/commons/Util.java
  java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationCFunctions.java
  java/src/main/java/com/powsybl/python/dynamic/DynamicSimulationContext.java
  java/src/main/java/com/powsybl/python/dynamic/PythonOutputVariablesSupplier.java
  java/src/test/java/com/powsybl/dataframe/dynamic/adders/OutputVariablesSupplierTest.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/dynamic/__init__.py
  pypowsybl/dynamic/impl/curve_mapping.py
  pypowsybl/dynamic/impl/output_variable_mapping.py
  pypowsybl/dynamic/impl/simulation.py
  pypowsybl/dynamic/impl/simulation_result.py
  tests/test_dynamic.py
Labels: breaking change

#893 Miscellaneous documentation fixes
  pypowsybl/network/impl/network.py
Labels: documentation, December 2024 release

#923 Fix sn property in network per unit view
  pypowsybl/network/impl/perunit.py
  tests/test_per_unit.py
Labels: December 2024 release
