Repository powsybl/pypowsybl, pull requests merged in 2025-04, with the labels that each got.

#938 Switch snapshot ci to new app and rework notification design
  .github/workflows/scripts/build_module.sh
  .github/workflows/scripts/check_snapshot_branch.sh
  .github/workflows/snapshot-ci.yml
Labels: breaking change

#962 Fix subscripts in per unit documentation
  docs/user_guide/per_unit.rst
Labels: Release 03/2025

#974 Update to PowSyBl dependencies 2025.0.0
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  data/rao/rao_parameters.json
  docs/reference/dynamic.rst
  docs/user_guide/dynamic.rst
  integration_tests/test_dynawo.py
  java/pom.xml
  java/pypowsybl/pom.xml
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/AbstractAutomationSystemSeries.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/AbstractDynamicModelSeries.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/AbstractEquipmentAdder.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/AbstractEquipmentSeries.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/DynamicMappingHandler.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/DynamicTwoLevelOverloadManagementSystemAdder.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-commons/resource-config.json
  java/pypowsybl/src/test/java/com/powsybl/dataframe/dynamic/adders/DynamicModelsAdderTest.java
  java/pypowsybl/src/test/resources/nad.svg
  pypowsybl/_pypowsybl.pyi
  pypowsybl/dynamic/impl/model_mapping.py
  pypowsybl/network/impl/util.py
  tests/test_dynamic.py
  tests/test_loadflow.py
  tests/test_network.py
  tests/test_rao.py
  tests/test_security_analysis.py
  tests/test_sensitivity_analysis.py
Labels: Release 03/2025

#953 Adding terminals connection action
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/security.rst
  java/pypowsybl/src/main/java/com/powsybl/python/security/SecurityAnalysisCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/security/impl/security.py
  tests/test_security_analysis.py
Labels: Release 03/2025

#963 Add voltage_level_details parameter
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/user_guide/network_visualization.rst
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/nad_parameters.py
  tests/test_network.py
Labels: Release 03/2025

#979 Fail early if crac is not valid
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoCFunctions.java
Labels: Release 03/2025

#976 adds style parameters to the NadProfile
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/network_visualization.rst
  java/pypowsybl/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-network-area-diagram/resource-config.json
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/nad_profile.py
  pypowsybl/network/impl/network.py
Labels: Release 03/2025

#959 Add JSON file content to ContingencyContainer
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  data/contingencies.json
  docs/user_guide/security.rst
  java/pypowsybl/src/main/java/com/powsybl/python/contingency/ContingencyContainer.java
  java/pypowsybl/src/main/java/com/powsybl/python/contingency/ContingencyContainerImpl.java
  java/pypowsybl/src/main/java/com/powsybl/python/security/SecurityAnalysisCFunctions.java
  java/pypowsybl/src/test/java/com/powsybl/python/contingency/ContingencyContainerTest.java
  java/pypowsybl/src/test/resources/contingencies.json
  pypowsybl/_pypowsybl.pyi
  pypowsybl/security/impl/contingency_container.py
  tests/test_security_analysis.py
Labels: Release 03/2025

#985 Get tap phase shift from transformer dataframes
  java/pypowsybl/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/pypowsybl/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  tests/test_network.py
Labels: Release 06/2025

#986 Check is a file is a loadable network
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/reference/network.rst
  java/pypowsybl/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/__init__.py
  pypowsybl/network/impl/network_creation_util.py
  tests/test_network.py
Labels: Release 06/2025

#961 Add monitoring and full parameters mapping to Rao api
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  java/pypowsybl/pom.xml
  java/pypowsybl/src/main/java/com/powsybl/python/commons/CTypeUtil.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/Util.java
  java/pypowsybl/src/main/java/com/powsybl/python/loadflow/LoadFlowCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/loadflow/LoadFlowCUtils.java
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoContext.java
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoUtils.java
  java/pypowsybl/src/main/java/com/powsybl/python/security/SecurityAnalysisCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/security/SecurityAnalysisCUtils.java
  java/pypowsybl/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/sensitivity/SensitivityAnalysisCUtils.java
  java/pypowsybl/src/main/java/com/powsybl/python/shortcircuit/ShortCircuitAnalysisCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/shortcircuit/ShortCircuitAnalysisCUtils.java
  java/pypowsybl/src/test/java/com/powsybl/python/rao/RaoUtilsTests.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/rao/__init__.py
  pypowsybl/rao/impl/loadflow_and_sensitivity_parameters.py
  pypowsybl/rao/impl/multithreading_parameters.py
  pypowsybl/rao/impl/not_optimized_cnecs_parameters.py
  pypowsybl/rao/impl/objective_function_parameters.py
  pypowsybl/rao/impl/parameters.py
  pypowsybl/rao/impl/range_action_optimization_parameters.py
  pypowsybl/rao/impl/rao.py
  pypowsybl/rao/impl/second_preventive_rao_parameters.py
  pypowsybl/rao/impl/topo_optimization_parameters.py
  tests/test_rao.py
Labels: Release 06/2025
