Repository powsybl/pypowsybl, pull requests merged in 2025-07, with the labels that each got.

#1006 Expose rao result as dataframes
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  data/rao/12_node_network.uct
  data/rao/N-1_case_crac_curative.json
  data/rao/rao_parameters_with_curative.json
  docs/user_guide/rao.rst
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoDataframes.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/rao/impl/rao_result.py
  tests/test_rao.py
Labels: Release 06/2025

#1005 Asynchronous loadflow run
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  docs/user_guide/loadflow.rst
  docs/user_guide/network.rst
  java/pypowsybl/src/main/java/com/powsybl/python/commons/Util.java
  java/pypowsybl/src/main/java/com/powsybl/python/loadflow/LoadFlowCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/grid2op/impl/backend.py
  pypowsybl/loadflow/__init__.py
  pypowsybl/loadflow/impl/loadflow.py
  pypowsybl/loadflow/impl/loadflow_results_future_wrapper.py
  pypowsybl/network/impl/network.py
  pypowsybl/network/impl/network_creation_util.py
  requirements.txt
  tests/test_async_loadflow.py
Labels: Release 06/2025

#1041 Add PARTIAL_FAILURE support for RaoComputationStatus
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/user_guide/rao.rst
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoCFunctions.java
  pypowsybl/_pypowsybl.pyi
Labels: bug, Release 06/2025

#1044 Upgrade to dependencies 2025.1.0
  .github/workflows/dev-ci.yml
  .github/workflows/full-ci.yml
  .github/workflows/release-ci.yml
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  data/rao/rao_parameters.json
  data/rao/rao_parameters_with_curative.json
  docs/user_guide/flowdecomposition.rst
  java/pom.xml
  java/pypowsybl/src/main/java/com/powsybl/dataframe/dynamic/adders/AbstractEquipmentSeries.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/loadflow/validation/InMemoryValidationWriter.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/loadflow/validation/SvcValidationData.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/loadflow/validation/Validations.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/network/adders/OperationalLimitsDataframeAdder.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/network/adders/SvcDataframeAdder.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/java/com/powsybl/python/flow_decomposition/XnecWithDecompositionContext.java
  java/pypowsybl/src/main/java/com/powsybl/python/network/NetworkAreaDiagramUtil.java
  java/pypowsybl/src/main/java/com/powsybl/python/network/NetworkCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/network/SingleLineDiagramUtil.java
  java/pypowsybl/src/main/java/com/powsybl/python/rao/RaoCFunctions.java
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-diagram-util/reflect-config.json
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-dynawo-commons/resource-config.json
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-entsoe-commons/resource-config.json
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-loadflow-api/resource-config.json
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-network-area-diagram/resource-config.json
  java/pypowsybl/src/main/resources/META-INF/native-image/com.powsybl/powsybl-single-line-diagram-core/reflect-config.json
  java/pypowsybl/src/test/java/com/powsybl/dataframe/dynamic/adders/EventModelsAdderTest.java
  java/pypowsybl/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  java/pypowsybl/src/test/java/com/powsybl/dataframe/network/adders/NetworkElementAddersTest.java
  java/pypowsybl/src/test/resources/nad.svg
  java/pypowsybl/src/test/resources/sld.svg
  pypowsybl/_pypowsybl.pyi
  pypowsybl/network/impl/network.py
  pypowsybl/rao/impl/parameters.py
  pypowsybl/rao/impl/topo_optimization_parameters.py
  tests/battery.xiidm
  tests/test_java_perunit.py
  tests/test_loadflow.py
  tests/test_network.py
  tests/test_network_elements_creation.py
  tests/test_network_modification.py
  tests/test_per_unit.py
  tests/test_rao.py
Labels: breaking change, Release 06/2025

#1047 Complete integration of IIDM v1.14
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/user_guide/flowdecomposition.rst
  docs/user_guide/network.rst
  java/pypowsybl/src/main/java/com/powsybl/dataframe/BaseDataframeMapperBuilder.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/DataframeHandler.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/OptionalIntSeriesMapper.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/impl/DefaultDataframeHandler.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/impl/Series.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/network/NetworkDataframes.java
  java/pypowsybl/src/main/java/com/powsybl/dataframe/network/adders/RatioTapChangerDataframeAdder.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/CommonCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/java/com/powsybl/python/dataframe/CDataframeHandler.java
  java/pypowsybl/src/test/java/com/powsybl/dataframe/network/NetworkDataframesTest.java
  pypowsybl/network/impl/network.py
  pypowsybl/utils/impl/util.py
  tests/test_java_perunit.py
  tests/test_network.py
  tests/test_network_elements_creation.py
  tests/test_per_unit.py
Labels: breaking change, Release 06/2025

#996 Dynamic simulation parameters
  cpp/powsybl-cpp/powsybl-cpp.cpp
  cpp/powsybl-cpp/powsybl-cpp.h
  cpp/pypowsybl-cpp/bindings.cpp
  cpp/pypowsybl-java/powsybl-api.h
  docs/reference/dynamic.rst
  docs/user_guide/dynamic.rst
  integration_tests/models.par
  integration_tests/network.par
  integration_tests/solvers.par
  integration_tests/test_dynawo.py
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblApiHeader.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/PyPowsyblConfiguration.java
  java/pypowsybl/src/main/java/com/powsybl/python/commons/Util.java
  java/pypowsybl/src/main/java/com/powsybl/python/dynamic/DynamicSimulationCFunctions.java
  java/pypowsybl/src/main/java/com/powsybl/python/dynamic/DynamicSimulationContext.java
  java/pypowsybl/src/main/java/com/powsybl/python/dynamic/DynamicSimulationParametersCUtils.java
  pypowsybl/_pypowsybl.pyi
  pypowsybl/dynamic/__init__.py
  pypowsybl/dynamic/impl/parameters.py
  pypowsybl/dynamic/impl/simulation.py
  tests/test_dynamic.py
  tests/test_security_analysis.py
Labels: breaking change, Release 06/2025

#1000 Minor doc fixes
  pypowsybl/network/impl/network.py
Labels: Release 06/2025
